### ISSUE TITLE
Feature request for C++

### ISSUE THREAD

**Issue by Fildo7525** [SmiteshP/nvim-navic#105]
When writing code in multiple files, there are different definitions and declarations in different places.
The winbar is different for both versions:
Header file
![Screenshot from 2023-04-15 22-58-02](https://user-images.githubusercontent.com/59179935/232252851-a15e7b67-5b09-4ae4-b794-beaceb597503.png)
source file:
![Screenshot from 2023-04-15 22-59-43](https://user-images.githubusercontent.com/59179935/232252912-0f3d93c1-63fc-40fc-a8d1-a09551dd66f4.png)

If both of them looked the same it would be great. My preference is the first one. One thing That would be great is if the parameters were shown for functions and methods. This could be controlled by a flag because not all people would like that.

**Comment by SmiteshP** [comment]
> If both of them looked the same it would be great.

This looks different because thats how the LSP is providing the data. You could write custom function for you winbar in C++ files that would find and replace the `::` with separators.

> One thing That would be great is if the parameters were shown for functions and methods.

Again this is not possible as LSP doesn't provide this data. However you could use the get_data function instead of the get_location function, and access the node's position and have some regex logic to parse the line and extract whatever information you want. And then combine it together into a string that can be displayed.
