### ISSUE TITLE
Does not work directly after opening the buffer

### ISSUE THREAD

**Issue by Mo8it** [SmiteshP/nvim-navic#3]
After opening a buffer and after the LSP server is started, the plugin takes a long time to show in lualine! This is the case with Julia-LSP and clangd (for c++).
Any idea how to debug?

**Comment by SmiteshP** [comment]
Yep! This is expected. The lsp server doesn't return data immediately... takes about 3-4 seconds before it starts returning results. I don't think there is any way to solve this.

**Comment by Mo8it** [comment]
No, it is more than 30 sec. I can record it if you want.

**Comment by B4rc1** [comment]
maybe this will help?: https://github.com/j-hui/fidget.nvim

**Comment by Mo8it** [comment]
fidget did not work for me, but I can now describe the bug with more details.
After entering a buffer and after the language server is started, navigating the code does not activate navic. Only after entering the INSERT mode and then navigating, navic is activated. See GIF with clangd with C++:

![demo](https://user-images.githubusercontent.com/76752051/173442640-5719075c-992b-4ff9-bcbd-186229168771.gif)

**Comment by SmiteshP** [comment]
>fidget did not work for me, but I can now describe the bug with more details.
After entering a buffer and after the language server is started, navigating the code does not activate navic. Only after entering the INSERT mode and then navigating, navic is activated. See GIF with clangd with C++:

Yep! This is the expected behaviour. Right now, the autocommand for updating is getting triggered at InsertLeave, CursorHold and BufEnter. So when you open a file and don't move around your cursor.. the autocommand isn't triggering even though LSP is ready to send information. One way to solve this might be to keep polling lsp server, but that might not be good for performance.
