### ISSUE TITLE
Feature request: pluggable resolution strategies?

### ISSUE THREAD

**Issue by benfowler** [SmiteshP/nvim-navic#6]
Hi Smitesh! Thanks for your great work on these plugins :-) 

I'm currently trying to incorporate _both_ `nvim-gps` and `nvim-navic` into my own Lua module to give me selectable strategies (either Treesitter or LSP, depending on language).

The reason why I would want to do something like this, is because:

1. Treesitter is way quicker than LSP, and is really ideally suited to this kind of plugin. However, it imposes maintenance overhead on you in `nvim-gps`
2. LSP can be more accurate, but is potentially slower; constantly calling out to LSP mightn't be the best use of LSP at all times.
3. Also -- I've yet to run into LSP server conflicts with `nvim-navic`, but it does not seem like fun to try and sort out in my LSP configuration, especially if `nvim-gps` does an adequate job.

What are you thoughts about this? Did you have any plans to perhaps consolidate these two plugins and expose a way to configure sources per filetype -- or shall I go ahead and assume that these plugins will remain separate going forward?

**Comment by SmiteshP** [comment]
> Treesitter is way quicker than LSP, and is really ideally suited to this kind of plugin
> LSP can be more accurate, but is potentially slower; constantly calling out to LSP mightn't be the best use of LSP at all times.

Yes, Treesitter might be quicker than LSP in response time. But there is no need to worry about performance issues. nvim-navic only makes call to LSP occasionally to get updated info on `BufEnter`, `InsertLeave` and `CursorHold` events. Also, its an asynchronous call to LSP so it doesn't block neovim's runtime. Whereas, nvim-gps used to make calls to treesitter and performs regex on the data for every `CursorMoved` event.

Treesitter isn't ideal for this task. nvim-gps isn't able to support all languages because of different quirks of some language's treesitter parser. There were some cases where I have wrote hacky queries to capture required information. Whereas LSP provides all this context information basically on a silver platter for us 😆 

> Also -- I've yet to run into LSP server conflicts with nvim-navic, but it does not seem like fun to try and sort out in my LSP configuration, especially if nvim-gps does an adequate job.

I agree that setting up nvim-gps was much easier by just using `gps.setup()`, but setting this up isn't that bad. You just have to add `on_attach = require("nvim-navic").attach` where ever you are setting up your lsp servers. 🤷🏽‍♂️ 
 
> What are you thoughts about this? Did you have any plans to perhaps consolidate these two plugins and expose a way to configure sources per filetype -- or shall I go ahead and assume that these plugins will remain separate going forward?

Nope, I am not planning on combining these two plugins. In fact I want to deprecate nvim-gps once I am sure that I have ironed out all the bugs in nvim-navic.
