### ISSUE TITLE
[feature request] Customize events used to update context

### ISSUE THREAD

**Issue by edementyev** [SmiteshP/nvim-navic#82]
Hi! First of all thank you for an amazing plugin, I use it in winbar with my heirline setup and it really is a beauty!
For this request, I would like to be able to select on which events `update_context` is triggered (specifically, opt out of CursorMoved). Would you consider (a PR) adding such option to setup? Thanks

**Comment by SmiteshP** [comment]
Yeah definitely can do that. I would be difficult to add option to `setup` function, it would have to be an option to the `attach` function 🤔 . Maybe a better way we can do this is to add a buffer variable something like `navic_lazy_update` or something, so that it will allow people to opt out of cursormoved updates on large files by setting up some auto commands.

**Comment by edementyev** [comment]
@SmiteshP thank you!
